// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ContactTemplate(lang string, translations map[string]map[string]string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-white dark:bg-gray-800 p-8 rounded-lg shadow-lg\"><h3 class=\"text-2xl font-bold text-indigo-600 dark:text-pink-400 mb-4\">Contact Information</h3><p class=\"text-gray-700 dark:text-gray-200 mb-2\"><strong>Address:</strong> 2 avenue de Boran, 60260 Lamorlaye</p><p class=\"text-gray-700 dark:text-gray-200 mb-2\"><strong>Phone:</strong> +33 7 69 52 77 59</p><p class=\"text-gray-700 dark:text-gray-200 mb-2\"><strong>Email:</strong> <a href=\"mailto:beetswouter@gmail.com\" class=\"text-indigo-600 dark:text-pink-400 hover:underline\">beetswouter@gmail.com</a></p><p class=\"text-gray-700 dark:text-gray-200\"><strong>GitHub:</strong> <a href=\"https://github.com/wouterbeets\" target=\"_blank\" class=\"text-indigo-600 dark:text-pink-400 hover:underline\">wouterbeets</a></p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
