// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"html/template"
)

func EducationTemplate(data map[string]interface{}) template.HTML {
	return template.HTML(`
` + func() template.HTML {
		var educationHTML template.HTML
		for _, item := range data["EducationItems"].([]map[string]interface{}) {
			educationHTML += template.HTML(`
<div class="education-item">
    <h3>` + item["Title"].(string) + `</h3>
    <span class="institution">` + item["Institution"].(string) + `</span>
    <span class="period">` + item["Period"].(string) + `</span>
</div>
`)
		}
		return educationHTML
	}() + `
`)
}

var _ = templruntime.GeneratedTemplate
